Repository operate-first/SRE, pull requests merged in 2020-12, with the labels that each got.

#29 Add CI files and fix linting errors
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  dashboards/README.md
  runbooks/TEMPLATE.md
  runbooks/jupyterhub.md
  yamllint-config.yaml
Labels: approved, size/M

#17 Add grafana dashboard for jupyterhub
  dashboards/Jupyterhub-dashboard.json
Labels: approved, size/XXL

#30 Update dashboard README
  dashboards/README.md
Labels: approved, size/XS
