Repository operate-first/SRE, pull requests merged in 2021-02, with the labels that each got.

#53 Update README
  README.md
Labels: approved, size/S

#54 Add monitoring dashboards
  dashboards/jupyterhub-sli-slo.json
  dashboards/jupyterhub-usage.json
  dashboards/opf-availability.json
Labels: approved, lgtm, size/XXL

#55 Update owners file.
  OWNERS
Labels: approved, size/S

#64 Update JH SLI dashboard
  dashboards/jupyterhub-sli-slo.json
Labels: approved, lgtm, size/XXL

#65 Update JH usage dashboard
  dashboards/jupyterhub-usage.json
Labels: approved, lgtm, size/S
