Repository operate-first/SRE, pull requests merged in 2021-04, with the labels that each got.

#244 fix: JupyterHub runbook feature file links
  runbooks/jupyterhub.md
Labels: approved, size/S

#255 Update opf-availability dashboard json
  dashboards/opf-availability.json
Labels: approved, lgtm, size/XL

#257 remove JH dashboard jsons
  dashboards/jupyterhub-sli-slo.json
  dashboards/jupyterhub-usage.json
Labels: approved, size/XXL

#258 Add kernel restart feature link to jh nb.
  runbooks/jupyterhub.md
Labels: approved, lgtm, size/M

#262 Fix grafana links in JH runbook
  runbooks/jupyterhub.md
Labels: approved, size/XS
