Repository operate-first/sre, pull requests merged in 2022-05, with the labels that each got.

#12 Add Chaos Engineering and Testing ADR
  ADRs/RH/SIG-SRE/ADR-00004-Chaos-Testing-and-Engineering.md
Labels: approved, size/M, lgtm

#11 Adding first draft of ADR for the purposes of documenting personas
  ADRs/RH/SIG-SRE/ADR-00002 Personas related to Managed Services.md
Labels: approved, size/L, lgtm

#14 Add Aaron as a reviewer
  OWNERS
Labels: approved, size/XS, lgtm

#15 Add Amber as a reviewer
  OWNERS
Labels: approved, size/XS, lgtm
