Repository operate-first/sre, pull requests merged in 2022-08, with the labels that each got.

#17 Incident management process first draft
  process/incident_management.md
  process/resources/im_flowchart.png
Labels: approved, size/L, lgtm

#27 SIGSRE-65: Add SLO Bootstrap Guide
  slo_bootstrap_guide.md
Labels: approved, size/M, lgtm

#26 README.md for SIGSRE-125
  ADRs/RH/README.md
  README.md
Labels: approved, size/M

#29 Add descriptions for the remaining documents.
  README.md
Labels: size/S, approved

#30 couple tiny updates
  README.md
Labels: approved, size/XS, lgtm

#31 Add Hilliary to reviewers
  OWNERS
Labels: approved, size/XS, lgtm
