Repository operate-first/sre, pull requests merged in 2022-10, with the labels that each got.

#35 Remove Dom and Dom from reviewers list
  OWNERS
Labels: size/XS

#36 Revert "Fix a typo and reorder the introduction of SLO and SLI"
  slo_bootstrap_guide.md
Labels: size/XS

#37 Cleanup pass to consolidate markdownlint and spelling corrections
  ADRs/RH/README.md
  ADRs/RH/SIG-SRE/ADR-00000 Template.md
  ADRs/RH/SIG-SRE/ADR-00001 Document architecture decisions using the Architecture Decision Records approach and define their templates.md
  ADRs/RH/SIG-SRE/ADR-00002 Personas related to Managed Services.md
  ADRs/RH/SIG-SRE/ADR-00004-Chaos-Testing-and-Engineering.md
  ADRs/RH/SIG-SRE/ADR-00005 SLO Lifecycle.md
  ADRs/RH/SIG-SRE/ADR-00006 SLO RACI Chart.md
  ADRs/RH/SIG-SRE/ADR-00007-Error-Budget-Policy.md
  ADRs/RH/SIG-SRE/README.md
  README.md
  picking_good_slis.md
  picking_good_slos.md
  process/incident_management.md
  prometheus_alerting_consistency.md
  slo_bootstrap_guide.md
  sre_maturity.md
Labels: approved, size/L, lgtm

#47 publishing to the home directory instead of subdir
  .github/workflows/sig-sre.yml
Labels: size/XS, lgtm

#38 proposing a community of practice roadmap
  sig-roadmap.md
Labels: size/M, lgtm

#42 Content changes toward being a full SIG
  README.md
Labels: size/L, lgtm

#49 adding @jeremyeder fixes we missed
  README.md
Labels: approved, size/XS, lgtm

#48 update TOC, add missing linked files
  CONTRIBUTING.md
  README.md
  _toc.yml
  charter.md
  sig-roadmap.md
Labels: size/S

#50 fix anchor links maturity, add info pdf download
  sre-coloring-book/red-hat-sre-coloring-book.md
  sre_maturity.md
Labels: kind/bug, kind/website, size/M, lgtm

#51 Contribution guidelines -- mostly referential content
  CONTRIBUTING.md
Labels: size/S, lgtm

#52 adding ga to jupyter book
  _config.yml
Labels: kind/metrics, kind/website, kind/marketing, size/XS, lgtm, kind/sigs
